### ISSUE TITLE
Demonstration run from README is not replicable

### ISSUE THREAD

**Issue by salfaris** [dialoa/imagify#17]
Hi @jdutant, great package, I love the idea and the potential use cases.

I tried to do the demo run you have in the README. In particular, I went down the Quarto route by cloning the repo and ran `make quarto && open example-quarto/example.html` and am not able to replicate the doc.

I am getting a `<LaTeX content not imagified>` for all the contents supposedly filtered by `imagify` as can be seen in the attached image below.

<img width="1512" alt="Screenshot 2024-08-05 at 13 07 40" src="https://github.com/user-attachments/assets/5bd2cf82-26f1-4f16-9746-5aaf832f462f">

I am using Quarto version 1.5.55 and I have tested the output HTML on both Safari and Google Chrome and neither is working.

Best,
Salman

**Comment by jdutant** [comment]
Hi @salfaris , thanks for your interest in the filter (and apologies for a late reply). 

The default example runs fine on my system (Quarto 1.6). I'm not sure what problem you face.

**LaTeX content not imagified** text in output means that Imagify has tried and failed to convert the TeX code. The output log would tell you more. There's a 'debug' option to get more informative output.

A thought: could it be that LaTeX isn't installed on your system outside of Quarto? To convert LaTeX/TikZ to SVG, the filter relies on a LaTeX installation (and its package dvisvgm). Quarto includes a small LaTeX installation to generate PDFs but (as far as I know) the filter can't use it. So, the filter needs LaTeX installed on your system (TexLive or MikTeX, for instance).
